### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/io.github.trigg.discover_overlay#12]
Flathub allows changelogs for each new release - can these be automated?

**Comment by trigg** [comment]
Is this the changelog in the XML file?

https://github.com/flathub/io.github.trigg.discover_overlay/blob/2a58d01edcee6b3faefcdc3960c9cb7c7fcfbb22/io.github.trigg.discover_overlay.appdata.xml#L29

It may be possible to automate it but I already have manual steps to do a flathub release and it doesn't add much

**Comment by Victor239** [comment]
I'm not certain which file it uses, I just know that when I updated Discover Overlay today it didn't have a changelog unlike other Flatpaks I use. Here are some other apps which do have changelogs: [ProtonUp-Qt](https://flathub.org/apps/net.davidotek.pupgui2) and [Bottles](https://flathub.org/apps/com.usebottles.bottles). It might be because your changelog is a hyperlink rather than a text-based changelog. 

Changelogs are important to me as it's time-consuming to find out what bugs have been fixed and features added in my software otherwise. I tend to defer updates for Flatpaks and Android apps until a later date if I have to visit another webpage to view them, and usually skip a few versions until I do so.

**Comment by trigg** [comment]
Oh I completely agree that changelogs are important.

What's odd is that I do supply a text-only changelog alongside the hyperlink.

It may be that it is prioritising url when it is present.

**Comment by trigg** [comment]
Made an attempt at sorting this by removing the URL links
I've also changed from plaintext to formatted in case that made a difference too.

Keeping the issue open until this is complete

**Comment by trigg** [comment]
https://flathub.org/apps/io.github.trigg.discover_overlay

That's taken by the website, so I'll close this now.

Feel free to reopen if it persists in any GUI application, but I think this will cover it

**Comment by Victor239** [comment]
Thanks!
