### ISSUE TITLE
Still getting the update error

### ISSUE THREAD

**Issue by wilsonephillips** [flathub/io.github.trigg.discover_overlay#30]
I saw that you closed the previous issue after bumping the flatpak dependencies, but I still see the same problem. Can you take another look at it please? Thank you so much.
____________
Looking for updates…

Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   io.github.trigg.discover_overlay

**Comment by trigg** [comment]
Will do! I probably forgot to press the publish button at the end...

**Comment by wilsonephillips** [comment]
It's all good now. Thank you!
