### ISSUE TITLE
GNOME 42 runtime is no longer supported

### ISSUE THREAD

**Issue by epic0421** [flathub/io.github.trigg.discover_overlay#7]
Got this message when running an update on my flatpaks today:

```
Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   io.github.trigg.discover_overlay
```

**Comment by trigg** [comment]
Thanks for the report, I'm assuming 43 is not deprecated yet but I can't find any information on supported versions

**Comment by trigg** [comment]
Info message about platform is gone on latest update, which should be filtering through the publish step any moment now.

Thanks again for the report!
